---
- name: Create sysop user
  user:
    name: "{{ user_name }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    create_home: yes
    home: /home/{{ user_name }}
    state: present

- name: Configure sudoers for wheel group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'

- name: Create .ssh directory with correct permissions
  file:
    path: /home/{{ user_name }}/.ssh
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0700'

- name: Copy authorized_keys file
  copy:
    src: files/authorized_keys
    dest: /home/{{ user_name }}/.ssh/authorized_keys
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0600'
    backup: yes

- name: Configure SSH daemon
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: '0644'
    validate: /usr/sbin/sshd -t -f %s
  notify: restart ssh