name: "uc-dev"
services:
  # Frontend
  uc-ui:
    container_name: uc-ui
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    environment:
      - NODE_ENV=production
    networks:
      - uc-network-dev
    depends_on:
      - uc-api
    restart: unless-stopped

  # Backend
  uc-api:
    container_name: uc-api
    build:
      context: ../backend/src
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=uc;Username=uc_user;Password=uc_pass
      - ConnectionStrings__Redis=redis:6379,password=redis_password
      - ServiceSettings__LoggingSettings__SeqServiceUrl=http://seq:5341
      - JwtSettings__Secret=uc-super-secret-key-with-minimum-32-characters-long
      - JwtSettings__Issuer=UCGame
      - JwtSettings__Audience=UCGameClient
    volumes:
      - ~/.nuget/packages:/root/.nuget/packages  # Cache nuget packages
    networks:
      - uc-network-dev
    depends_on:
      postgres:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
      seq:
        condition: service_healthy
    restart: unless-stopped


  #Infrastructure services (БД, кэш, брокер задач)
  postgres:
      container_name: uc-postgres
      image: postgres:17
      environment:
        POSTGRES_DB: uc
        POSTGRES_USER: uc_user
        POSTGRES_PASSWORD: uc_pass
      ports:
        - "5432:5432"
      volumes:
        - uc_postgres_data:/var/lib/postgresql/data
      networks:
        - uc-network-dev
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ailingo_user -d postgres -h localhost -p 5432"] 
        interval: 10s
        timeout: 5s
        retries: 5
      restart: unless-stopped

  # redis:
  #   container_name: uc-redis
  #   image: redis:7.2-alpine
  #   command: redis-server --appendonly yes
  #   environment:
  #     - REDIS_PASSWORD=redis_password
  #   volumes:
  #     - uc_redis_data:/data
  #     - ./infrastructure/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
  #   networks:
  #     - uc-network-dev
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 5

  seq:
    container_name: uc-seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "admin123" # zuevus work host is 7Nbgf3R9STyPuAG
    ports:
      - "5341:80"      # Web UI для просмотра логов
    volumes:
      - uc_seq_data:/data
    networks:
      - uc-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  uc-network-dev:
    driver: bridge

volumes:
  uc_postgres_data:
    driver: local
  # uc_redis_data:
  #   driver: local
  uc_seq_data:
    driver: local
  uc_nats_data:
    driver: local